name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - master
      - POC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Maven
        run: sudo apt-get update && sudo apt-get install -y maven

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Import GPG key
        run: |
            echo "$GPG_PRIVATE_KEY" | gpg --batch --import
        env:
            GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
            GPG_TTY: $(tty)

      - name: Build and test
        run: mvn clean verify -P coverage -DskipTests=true
        env:
          GPG_TTY: $(tty)
