name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install GPG
        run: sudo apt-get update && sudo apt-get install -y gnupg2

      - name: Setup GPG Home Directory
        run: |
            mkdir -p $HOME/.gnupg
            chmod 700 $HOME/.gnupg

      - name: Import GPG private key
        run: echo "$GPG_PRIVATE_KEY" | gpg --batch --import
        env:
            GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: List GPG Keys
        run: gpg --list-secret-keys --keyid-format LONG

      - name: Set GPG passphrase
        run: export GPG_PASSPHRASE=${{ secrets.GPG_PASSPHRASE }}

      - name: Build and Sign Artifacts
        run: |
            export GPG_TTY=$(tty)
            mvn clean verify -P coverage -Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }} \
            -Dgpg.homedir=$HOME/.gnupg \
            -Dgpg.executable=gpg2 \
            -Dgpg.defaultKeyring=true \
