name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Import GPG private key
        run: echo "$GPG_PRIVATE_KEY" | gpg --batch --import
        env:
            GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Set GPG passphrase
        run: export GPG_PASSPHRASE=${{ secrets.GPG_PASSPHRASE }}

      - name: Build and Sign Artifacts
        run: |
            export GPG_TTY=$(tty)
            mvn clean verify -Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }} \
