name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - master
      - POC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Maven
        run: sudo apt-get update && sudo apt-get install -y maven

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Import GPG private key
        run: echo "$GPG_PRIVATE_KEY" | gpg --batch --import
        env:
            GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Set GPG passphrase
        run: export GPG_PASSPHRASE=${{ secrets.GPG_PASSPHRASE }}

      - name: Build and Sign Artifacts
        run: mvn clean verify -Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }}
